name: CI
on: [push]
jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./ci/setup/setup.sh
      - run: ./ci/format.sh --check
  test:
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: ./ci/setup/setup.sh
      - run: ./ci/build-and-test.sh ${{matrix.configuration}}
  required-checks:
    name: Required checks
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    needs:
      - test
      - formatting
    steps:
      - run: |
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            exit 1
          fi
          if [[ "${{ needs.formatting.result }}" != "success" ]]; then
            exit 1
          fi
          exit 0
